name: Build

on:
  push:
    branches: [main, week-05-storybook-testing]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check build artifacts
        run: |
          if [ ! -d "dist" ] && [ ! -d "build" ] && [ ! -d ".next" ]; then
            echo "No build output directory found. Expected 'dist', 'build' or '.next'."
            exit 1
          fi
