name: Build

on:
  push:
    branches: [main, week-05-storybook-testing]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run storybook-build

      - name: Run Storybook tests
        run: npm run test-storybook

      # Optional: Collect and upload test coverage
      # - name: Collect coverage
      #   run: npx nyc report
      #   if: always()
      #   continue-on-error: true

      # Upload artifacts if tests fail
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: storybook-test-results
          path: |
            ./*-snapshots/
            ./coverage/
          retention-days: 7
  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check build artifacts
        run: |
          if [ ! -d "dist" ] && [ ! -d "build" ] && [ ! -d ".next" ]; then
            echo "No build output directory found. Expected 'dist', 'build' or '.next'."
            exit 1
          fi
